---
- name: Add azureuser to www-data group
  become: yes
  user:
    name: azureuser
    groups: www-data
    append: yes

- name: Create mediawiki directory
  file:
    path: "{{ mediawiki_directory }}"
    owner: "www-data"
    group: "www-data"
    state: directory

- name: Download mediawiki archive
  get_url:
    url: "{{ mediawiki_archive_url }}"
    dest: "/tmp/mediawiki.tar.gz"

- name: Uncompress mediawiki archive
  command:
    cmd: tar --strip-components=1 -xzf /tmp/mediawiki.tar.gz -C {{ mediawiki_directory }}

- name: Add write permissions to mediawiki directory
  file:
    path: "{{ mediawiki_directory }}"
    mode: 'g+w'
    recurse: true

- name: Configure mediawiki
  become: yes
  become_user: azureuser
  command:
    chdir: "{{ mediawiki_maintenance_directory }}"
    cmd: >
      php install.php --scriptpath /{{ mediawiki_name }} --dbname mediawiki --lang fr 
      --dbuser {{ mediawiki_db_user }} --dbpass {{ mediawiki_db_password }} 
      --pass {{ mediawiki_admin_password }} --dbserver {{ mediawiki_db_host }} 
      --server http://ADvm1 {{ mediawiki_title }} {{ mediawiki_admin_user }}
    creates: "{{ mediawiki_directory }}/LocalSettings.php"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['apache'] }}"
  run_once: yes

- name: Update mediawiki database
  become: yes
  become_user: azureuser
  command:
    chdir: "{{ mediawiki_maintenance_directory }}"
    cmd: php update.php --quick
  register: resultat
  changed_when: "'...done.' in resultat.stdout"
  run_once: yes
